// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EntityRepository is an autogenerated mock type for the EntityRepository type
type EntityRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields:
func (_m *EntityRepository) Create() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEntityRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntityRepository creates a new instance of EntityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntityRepository(t mockConstructorTestingTNewEntityRepository) *EntityRepository {
	mock := &EntityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
